Feature/update
hex-g/ishigami pull request #3
Opened 2019-05-02 03:25 UTC by SamuelLevi

__( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩__

# New things:
- Class Pedagogue / Student / Person
- Dynamic update

# Changes:
- Check constraint by text

# Removed:
-

__( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩__

2019-05-05 22:43 UTC, eiling approved these changes

2019-05-06 13:20 UTC, manoger approved these changes
# >.< Reviewed

2019-05-06 13:57 UTC, manoger requested changes
The Setters parameters can be final

2019-05-06 21:48 UTC, manoger approved these changes

2019-05-06 21:50 UTC, merged